#!/usr/bin/env python3
"""
Build script to update slideshow.js with images from the slideshow folder.
Run this script whenever you add or remove images from:
  - Slideshow Images/cropped images for slideshow/

Usage: python3 update-slideshow.py
"""

import os
import re

# Configuration
BASE_PATH = os.path.dirname(os.path.abspath(__file__))
SLIDESHOW_JS = os.path.join(BASE_PATH, "slideshow.js")

# Folder to scan for images (relative path)
IMAGE_FOLDERS = [
    "Slideshow Images/cropped images for slideshow"
]

# Supported image extensions
IMAGE_EXTENSIONS = ('.jpeg', '.jpg', '.png', '.webp')

def get_images_from_folders():
    """Scan folders and return list of image paths."""
    images = []

    for folder in IMAGE_FOLDERS:
        folder_path = os.path.join(BASE_PATH, folder)
        if not os.path.exists(folder_path):
            print(f"Warning: Folder not found: {folder}")
            continue

        for filename in sorted(os.listdir(folder_path)):
            if filename.lower().endswith(IMAGE_EXTENSIONS):
                # Skip non-VSCO versions if VSCO version exists
                if not filename.endswith('-VSCO.jpeg') and filename.endswith('.JPG'):
                    vsco_version = filename.replace('.JPG', '-VSCO.jpeg')
                    if os.path.exists(os.path.join(folder_path, vsco_version)):
                        continue

                image_path = f"{folder}/{filename}"
                images.append(image_path)

    return images

def generate_images_array(images):
    """Generate JavaScript array string for images."""
    lines = ["// Slideshow data - dynamically generated by update-slideshow.py"]
    lines.append("const slideshowImages = [")

    for img in images:
        lines.append(f'  {{ src: "{img}", alt: "Fifth Flora floral arrangement" }},')

    lines.append("];")
    return "\n".join(lines)

def update_slideshow_js(new_array):
    """Update slideshow.js with new images array."""
    with open(SLIDESHOW_JS, 'r') as f:
        content = f.read()

    # Pattern to match the existing slideshowImages array
    pattern = r'// Slideshow data.*?const slideshowImages = \[[\s\S]*?\];'

    if re.search(pattern, content):
        new_content = re.sub(pattern, new_array, content)
    else:
        # Fallback: replace just the array
        pattern = r'const slideshowImages = \[[\s\S]*?\];'
        new_content = re.sub(pattern, new_array.split('\n', 1)[1], content)

    with open(SLIDESHOW_JS, 'w') as f:
        f.write(new_content)

def main():
    print("Scanning image folders...")
    images = get_images_from_folders()
    print(f"Found {len(images)} images")

    print("Generating slideshow array...")
    new_array = generate_images_array(images)

    print("Updating slideshow.js...")
    update_slideshow_js(new_array)

    print(f"Done! slideshow.js updated with {len(images)} images.")
    print("\nImages included:")
    for img in images:
        print(f"  - {img}")

if __name__ == "__main__":
    main()
